import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument, Types } from 'mongoose';

export type ReportDocument = HydratedDocument<Report>;

/**
 * Report Schema
 * 
 * Fields:
 *  _id        Auto generated by MongoDB
 *  date       The date of the report
 *  task       A single task description
 *  startTime  The start time of the task
 *  endTime    The end time of the task
 *  createdAt  Auto generated timestamp when document is created
 *  updatedAt  Auto generated timestamp when document is updated
 *  user       foreign key
 */


@Schema({ timestamps: true }) 
export class Report {

  @Prop({ required: true })
  date: Date;

  @Prop({ required: true })
  task: string;

  @Prop({ required: true })
  startTime: string;

  @Prop({ required: true })
  endTime: string;

  /**
   * We will say that it is foriegn key.
   * referencing to the user model. 
   */

  @Prop({ type: Types.ObjectId, ref: 'User', required: true })
  user: Types.ObjectId;

  createdAt?: Date;
  updatedAt?: Date;
}

export const ReportSchema = SchemaFactory.createForClass(Report);
